import { REDUCER_ID } from "../_meta";

export const CREATE_MERCHANT = `${REDUCER_ID}/CREATE_MERCHANT`;
export const CREATE_MERCHANT_PENDING = `${REDUCER_ID}/CREATE_MERCHANT_PENDING`;
export const CREATE_MERCHANT_SUCCESS = `${REDUCER_ID}/CREATE_MERCHANT_SUCCESS`;
export const CREATE_MERCHANT_FAILURE = `${REDUCER_ID}/CREATE_MERCHANT_FAILURE`;

export const GET_MERCHANT = `${REDUCER_ID}/GET_MERCHANT`;
export const GET_MERCHANT_PENDING = `${REDUCER_ID}/GET_MERCHANT_PENDING`;
export const GET_MERCHANT_SUCCESS = `${REDUCER_ID}/GET_MERCHANT_SUCCESS`;
export const GET_MERCHANT_FAILURE = `${REDUCER_ID}/GET_MERCHANT_FAILURE`;

export const GET_MERCHANTS = `${REDUCER_ID}/GET_MERCHANTS`;
export const GET_MERCHANTS_PENDING = `${REDUCER_ID}/GET_MERCHANTS_PENDING`;
export const GET_MERCHANTS_SUCCESS = `${REDUCER_ID}/GET_MERCHANTS_SUCCESS`;
export const GET_MERCHANTS_FAILURE = `${REDUCER_ID}/GET_MERCHANTS_FAILURE`;

export const SYNC_MERCHANT = `${REDUCER_ID}/SYNC_MERCHANT`;
export const SYNC_MERCHANT_PENDING = `${REDUCER_ID}/SYNC_MERCHANT_PENDING`;
export const SYNC_MERCHANT_SUCCESS = `${REDUCER_ID}/SYNC_MERCHANT_SUCCESS`;
export const SYNC_MERCHANT_FAILURE = `${REDUCER_ID}/SYNC_MERCHANT_FAILURE`;

export const GET_TRANSACTIONS = `${REDUCER_ID}/GET_TRANSACTIONS`;
export const GET_TRANSACTIONS_PENDING = `${REDUCER_ID}/GET_TRANSACTIONS_PENDING`;
export const GET_TRANSACTIONS_SUCCESS = `${REDUCER_ID}/GET_TRANSACTIONS_SUCCESS`;
export const GET_TRANSACTIONS_FAILURE = `${REDUCER_ID}/GET_TRANSACTIONS_FAILURE`;

export const UPDATE_MERCHANT_PENDING = `${REDUCER_ID}/UPDATE_MERCHANT_PENDING`;
export const UPDATE_MERCHANT_SUCCESS = `${REDUCER_ID}/UPDATE_MERCHANT_SUCCESS`;
export const UPDATE_MERCHANT_FAILURE = `${REDUCER_ID}/UPDATE_MERCHANT_FAILURE`;

export const CREATE_CONTACT = `${REDUCER_ID}/CREATE_CONTACT`;
export const CREATE_CONTACT_PENDING = `${REDUCER_ID}/CREATE_CONTACT_PENDING`;
export const CREATE_CONTACT_SUCCESS = `${REDUCER_ID}/CREATE_CONTACT_SUCCESS`;
export const CREATE_CONTACT_FAILURE = `${REDUCER_ID}/CREATE_CONTACT_FAILURE`;

export const UPDATE_CONTACT_PENDING = `${REDUCER_ID}/UPDATE_CONTACT_PENDING`;
export const UPDATE_CONTACT_SUCCESS = `${REDUCER_ID}/UPDATE_CONTACT_SUCCESS`;
export const UPDATE_CONTACT_FAILURE = `${REDUCER_ID}/UPDATE_CONTACT_FAILURE`;

export const CREATE_LOCATION = `${REDUCER_ID}/CREATE_LOCATION`;
export const CREATE_LOCATION_PENDING = `${REDUCER_ID}/CREATE_LOCATION_PENDING`;
export const CREATE_LOCATION_SUCCESS = `${REDUCER_ID}/CREATE_LOCATION_SUCCESS`;
export const CREATE_LOCATION_FAILURE = `${REDUCER_ID}/CREATE_LOCATION_FAILURE`;

export const UPDATE_LOCATION_PENDING = `${REDUCER_ID}/UPDATE_LOCATION_PENDING`;
export const UPDATE_LOCATION_SUCCESS = `${REDUCER_ID}/UPDATE_LOCATION_SUCCESS`;
export const UPDATE_LOCATION_FAILURE = `${REDUCER_ID}/UPDATE_LOCATION_FAILURE`;

export const SYNC_LOCATION_PENDING = `${REDUCER_ID}/SYNC_LOCATION_PENDING`;
export const SYNC_LOCATION_SUCCESS = `${REDUCER_ID}/SYNC_LOCATION_SUCCESS`;
export const SYNC_LOCATION_FAILURE = `${REDUCER_ID}/SYNC_LOCATION_FAILURE`;

export const CREATE_LOCATION_OFFER = `${REDUCER_ID}/CREATE_LOCATION_OFFER`;
export const CREATE_LOCATION_OFFER_PENDING = `${REDUCER_ID}/CREATE_LOCATION_OFFER_PENDING`;
export const CREATE_LOCATION_OFFER_SUCCESS = `${REDUCER_ID}/CREATE_LOCATION_OFFER_SUCCESS`;
export const CREATE_LOCATION_OFFER_FAILURE = `${REDUCER_ID}/CREATE_LOCATION_OFFER_FAILURE`;

export const UPDATE_LOCATION_OFFER = `${REDUCER_ID}/UPDATE_LOCATION_OFFER`;
export const UPDATE_LOCATION_OFFER_PENDING = `${REDUCER_ID}/UPDATE_LOCATION_OFFER_PENDING`;
export const UPDATE_LOCATION_OFFER_SUCCESS = `${REDUCER_ID}/UPDATE_LOCATION_OFFER_SUCCESS`;
export const UPDATE_LOCATION_OFFER_FAILURE = `${REDUCER_ID}/UPDATE_LOCATION_OFFER_FAILURE`;

export const GET_INVOICES = `${REDUCER_ID}/GET_INVOICES`;
export const GET_INVOICES_PENDING = `${REDUCER_ID}/GET_INVOICES_PENDING`;
export const GET_INVOICES_SUCCESS = `${REDUCER_ID}/GET_INVOICES_SUCCESS`;
export const GET_INVOICES_FAILURE = `${REDUCER_ID}/GET_INVOICES_FAILURE`;

export const CREATE_INVOICES = `${REDUCER_ID}/CREATE_INVOICES`;
export const CREATE_INVOICES_PENDING = `${REDUCER_ID}/CREATE_INVOICES_PENDING`;
export const CREATE_INVOICES_SUCCESS = `${REDUCER_ID}/CREATE_INVOICES_SUCCESS`;
export const CREATE_INVOICES_FAILURE = `${REDUCER_ID}/CREATE_INVOICES_FAILURE`;

export const CREATE_PRODUCT = `${REDUCER_ID}/CREATE_PRODUCT`;
export const CREATE_PRODUCT_PENDING = `${REDUCER_ID}/CREATE_PRODUCT_PENDING`;
export const CREATE_PRODUCT_SUCCESS = `${REDUCER_ID}/CREATE_PRODUCT_SUCCESS`;
export const CREATE_PRODUCT_FAILURE = `${REDUCER_ID}/CREATE_PRODUCT_FAILURE`;

export const UPDATE_PRODUCT_PENDING = `${REDUCER_ID}/UPDATE_PRODUCT_PENDING`;
export const UPDATE_PRODUCT_SUCCESS = `${REDUCER_ID}/UPDATE_PRODUCT_SUCCESS`;
export const UPDATE_PRODUCT_FAILURE = `${REDUCER_ID}/UPDATE_PRODUCT_FAILURE`;

export const GET_MERCHANT_INVOICE = `${REDUCER_ID}/GET_MERCHANT_INVOICE`;
export const GET_MERCHANT_INVOICE_PENDING = `${REDUCER_ID}/GET_MERCHANT_INVOICE_PENDING`;
export const GET_MERCHANT_INVOICE_SUCCESS = `${REDUCER_ID}/GET_MERCHANT_INVOICE_SUCCESS`;
export const GET_MERCHANT_INVOICE_FAILURE = `${REDUCER_ID}/GET_MERCHANT_INVOICE_FAILURE`;

export const CREATE_DISPUTE = `${REDUCER_ID}/CREATE_DISPUTE`;
export const CREATE_DISPUTE_PENDING = `${REDUCER_ID}/CREATE_DISPUTE_PENDING`;
export const CREATE_DISPUTE_SUCCESS = `${REDUCER_ID}/CREATE_DISPUTE_SUCCESS`;
export const CREATE_DISPUTE_FAILURE = `${REDUCER_ID}/CREATE_DISPUTE_FAILURE`;

export const CREATE_ACCOUNT = `${REDUCER_ID}/CREATE_ACCOUNT`;
export const CREATE_ACCOUNT_PENDING = `${REDUCER_ID}/CREATE_ACCOUNT_PENDING`;
export const CREATE_ACCOUNT_SUCCESS = `${REDUCER_ID}/CREATE_ACCOUNT_SUCCESS`;
export const CREATE_ACCOUNT_FAILURE = `${REDUCER_ID}/CREATE_ACCOUNT_FAILURE`;

export const UPDATE_INVOICE = `${REDUCER_ID}/UPDATE_INVOICE`;
export const UPDATE_INVOICE_PENDING = `${REDUCER_ID}/UPDATE_INVOICE_PENDING`;
export const UPDATE_INVOICE_SUCCESS = `${REDUCER_ID}/UPDATE_INVOICE_SUCCESS`;
export const UPDATE_INVOICE_FAILURE = `${REDUCER_ID}/UPDATE_INVOICE_FAILURE`;

export const UPDATE_ACCOUNT = `${REDUCER_ID}/UPDATE_ACCOUNT`;
export const UPDATE_ACCOUNT_PENDING = `${REDUCER_ID}/UPDATE_ACCOUNT_PENDING`;
export const UPDATE_ACCOUNT_SUCCESS = `${REDUCER_ID}/UPDATE_ACCOUNT_SUCCESS`;
export const UPDATE_ACCOUNT_FAILURE = `${REDUCER_ID}/UPDATE_ACCOUNT_FAILURE`;

export const GET_ALL_INVOICE = `${REDUCER_ID}/GET_ALL_INVOICE`;
export const GET_ALL_INVOICE_PENDING = `${REDUCER_ID}/GET_ALL_INVOICE_PENDING`;
export const GET_ALL_INVOICE_SUCCESS = `${REDUCER_ID}/GET_ALL_INVOICE_SUCCESS`;
export const GET_ALL_INVOICE_FAILURE = `${REDUCER_ID}/GET_ALL_INVOICE_FAILURE`;

export const UPDATE_LOCATION_DETAILS = `${REDUCER_ID}/UPDATE_LOCATION_DETAILS_`;
export const UPDATE_LOCATION_DETAILS_PENDING = `${REDUCER_ID}/UPDATE_LOCATION_DETAILS_PENDING`;
export const UPDATE_LOCATION_DETAILS_SUCCESS = `${REDUCER_ID}/UPDATE_LOCATION_DETAILS_SUCCESS`;
export const UPDATE_LOCATION_DETAILS_FAILURE = `${REDUCER_ID}/UPDATE_LOCATION_DETAILS_FAILURE`;

export const CREATE_LOCATION_CUISINE = `${REDUCER_ID}/CREATE_LOCATION_CUISINE`;
export const CREATE_LOCATION_CUISINE_PENDING = `${REDUCER_ID}/CREATE_LOCATION_CUISINE_PENDING`;
export const CREATE_LOCATION_CUISINE_SUCCESS = `${REDUCER_ID}/CREATE_LOCATION_CUISINE_SUCCESS`;
export const CREATE_LOCATION_CUISINE_FAILURE = `${REDUCER_ID}/CREATE_LOCATION_CUISINE_FAILURE`;

export const UPDATE_LOCATION_CUISINE = `${REDUCER_ID}/UPDATE_LOCATION_CUISINE`;
export const UPDATE_LOCATION_CUISINE_PENDING = `${REDUCER_ID}/UPDATE_LOCATION_CUISINE_PENDING`;
export const UPDATE_LOCATION_CUISINE_SUCCESS = `${REDUCER_ID}/UPDATE_LOCATION_CUISINE_SUCCESS`;
export const UPDATE_LOCATION_CUISINE_FAILURE = `${REDUCER_ID}/UPDATE_LOCATION_CUISINE_FAILURE`;

export const GET__REDEEM_TRANSACTIONS = `${REDUCER_ID}/GET__REDEEM_TRANSACTIONS`;
export const GET__REDEEM_TRANSACTIONS_PENDING = `${REDUCER_ID}/GET__REDEEM_TRANSACTIONS_PENDING`;
export const GET__REDEEM_TRANSACTIONS_SUCCESS = `${REDUCER_ID}/GET__REDEEM_TRANSACTIONS_SUCCESS`;
export const GET__REDEEM_TRANSACTIONS_FAILURE = `${REDUCER_ID}/GET__REDEEM_TRANSACTIONS_FAILURE`;

export const UPDATE_REDEEM_TRANSACTIONS = `${REDUCER_ID}/UPDATE_REDEEM_TRANSACTIONS`;
export const UPDATE_REDEEM_TRANSACTIONS_PENDING = `${REDUCER_ID}/UPDATE_REDEEM_TRANSACTIONS_PENDING`;
export const UPDATE_REDEEM_TRANSACTIONS_SUCCESS = `${REDUCER_ID}/UPDATE_REDEEM_TRANSACTIONS_SUCCESS`;
export const UPDATE_REDEEM_TRANSACTIONS_FAILURE = `${REDUCER_ID}/UPDATE_REDEEM_TRANSACTIONS_FAILURE`;

export const APPROVE_MERCHANT = `${REDUCER_ID}/APPROVE_MERCHANT`;
export const APPROVE_MERCHANT_PENDING = `${REDUCER_ID}/APPROVE_MERCHANT_PENDING`;
export const APPROVE_MERCHANT_SUCCESS = `${REDUCER_ID}/APPROVE_MERCHANT_SUCCESS`;
export const APPROVE_MERCHANT_FAILURE = `${REDUCER_ID}/APPROVE_MERCHANT_FAILURE`;
