import { REDUCER_ID } from "../_meta";

export const GET_CUSTOMERS = `${REDUCER_ID}/GET_CUSTOMERS`;
export const GET_CUSTOMERS_PENDING = `${REDUCER_ID}/GET_CUSTOMERS_PENDING`;
export const GET_CUSTOMERS_SUCCESS = `${REDUCER_ID}/GET_CUSTOMERS_SUCCESS`;
export const GET_CUSTOMERS_FAILURE = `${REDUCER_ID}/GET_CUSTOMERS_FAILURE`;

export const GET_CUSTOMER_TRANSACTION = `${REDUCER_ID}/GET_CUSTOMER_TRANSACTION`;
export const GET_CUSTOMER_TRANSACTION_PENDING = `${REDUCER_ID}/GET_CUSTOMER_TRANSACTION_PENDING`;
export const GET_CUSTOMER_TRANSACTION_SUCCESS = `${REDUCER_ID}/GET_CUSTOMER_TRANSACTION_SUCCESS`;
export const GET_CUSTOMER_TRANSACTION_FAILURE = `${REDUCER_ID}/GET_CUSTOMER_TRANSACTION_FAILURE`;

export const GET_CUSTOMER_REDEEM = `${REDUCER_ID}/GET_CUSTOMER_REDEEM`;
export const GET_CUSTOMER_REDEEM_PENDING = `${REDUCER_ID}/GET_CUSTOMER_REDEEM_PENDING`;
export const GET_CUSTOMER_REDEEM_SUCCESS = `${REDUCER_ID}/GET_CUSTOMER_REDEEM_SUCCESS`;
export const GET_CUSTOMER_REDEEM_FAILURE = `${REDUCER_ID}/GET_CUSTOMER_REDEEM_FAILURE`;

export const UPDATE_CUSTOMER_REDEEM = `${REDUCER_ID}/UPDATE_CUSTOMER_REDEEM`;
export const UPDATE_CUSTOMER_REDEEM_PENDING = `${REDUCER_ID}/UPDATE_CUSTOMER_REDEEM_PENDING`;
export const UPDATE_CUSTOMER_REDEEM_SUCCESS = `${REDUCER_ID}/UPDATE_CUSTOMER_REDEEM_SUCCESS`;
export const UPDATE_CUSTOMER_REDEEM_FAILURE = `${REDUCER_ID}/UPDATE_CUSTOMER_REDEEM_FAILURE`;
