import { REDUCER_ID } from "../_meta";

export const GET_SALES_REPORT = `${REDUCER_ID}/GET_SALES_REPORT`;
export const GET_SALES_REPORT_PENDING = `${REDUCER_ID}/GET_SALES_REPORT_PENDING`;
export const GET_SALES_REPORT_SUCCESS = `${REDUCER_ID}/GET_SALES_REPORT_SUCCESS`;
export const GET_SALES_REPORT_FAILURE = `${REDUCER_ID}/GET_SALES_REPORT_FAILURE`;

export const GET_SALES_STATS = `${REDUCER_ID}/GET_SALES_STATS`;
export const GET_SALES_STATS_PENDING = `${REDUCER_ID}/GET_SALES_STATS_PENDING`;
export const GET_SALES_STATS_SUCCESS = `${REDUCER_ID}/GET_SALES_STATS_SUCCESS`;
export const GET_SALES_STATS_FAILURE = `${REDUCER_ID}/GET_SALES_STATS_FAILURE`;

export const GET_INVOICE = `${REDUCER_ID}/GET_INVOICE`;
export const GET_INVOICE_PENDING = `${REDUCER_ID}/GET_INVOICE_PENDING`;
export const GET_INVOICE_SUCCESS = `${REDUCER_ID}/GET_INVOICE_SUCCESS`;
export const GET_INVOICE_FAILURE = `${REDUCER_ID}/GET_INVOICE_FAILURE`;

export const GET_OFFER = `${REDUCER_ID}/GET_OFFER`;
export const GET_OFFER_PENDING = `${REDUCER_ID}/GET_OFFER_PENDING`;
export const GET_OFFER_SUCCESS = `${REDUCER_ID}/GET_OFFER_SUCCESS`;
export const GET_OFFER_FAILURE = `${REDUCER_ID}/GET_OFFER_FAILURE`;

export const GET_TRANSACTIONS = `${REDUCER_ID}/GET_TRANSACTIONS`;
export const GET_TRANSACTIONS_PENDING = `${REDUCER_ID}/GET_TRANSACTIONS_PENDING`;
export const GET_TRANSACTIONS_SUCCESS = `${REDUCER_ID}/GET_TRANSACTIONS_SUCCESS`;
export const GET_TRANSACTIONS_FAILURE = `${REDUCER_ID}/GET_TRANSACTIONS_FAILURE`;

export const GET_MERCHANT_DETAILS = `${REDUCER_ID}/GET_MERCHANT_DETAILS`;
export const GET_MERCHANT_DETAILS_PENDING = `${REDUCER_ID}/GET_MERCHANT_DETAILS_PENDING`;
export const GET_MERCHANT_DETAILS_SUCCESS = `${REDUCER_ID}/GET_MERCHANT_DETAILS_SUCCESS`;
export const GET_MERCHANT_DETAILS_FAILURE = `${REDUCER_ID}/GET_MERCHANT_DETAILS_FAILURE`;

export const GET_DISPUTE = `${REDUCER_ID}/GET_DISPUTE`;
export const GET_DISPUTE_PENDING = `${REDUCER_ID}/GET_DISPUTE_PENDING`;
export const GET_DISPUTE_SUCCESS = `${REDUCER_ID}/GET_DISPUTE_SUCCESS`;
export const GET_DISPUTE_FAILURE = `${REDUCER_ID}/GET_DISPUTE_FAILURE`;

export const GET_DISPUTE_STAT = `${REDUCER_ID}/GET_DISPUTE_STAT`;
export const GET_DISPUTE_STAT_PENDING = `${REDUCER_ID}/GET_DISPUTE_STAT_PENDING`;
export const GET_DISPUTE_STAT_SUCCESS = `${REDUCER_ID}/GET_DISPUTE_STAT_SUCCESS`;
export const GET_DISPUTE_STAT_FAILURE = `${REDUCER_ID}/GET_DISPUTE_STAT_FAILURE`;

export const SET_DISPUTE_MESSAGE = `${REDUCER_ID}/SET_DISPUTE_MESSAGE`;
export const SET_DISPUTE_MESSAGE_PENDING = `${REDUCER_ID}/SET_DISPUTE_MESSAGE_PENDING`;
export const SET_DISPUTE_MESSAGE_SUCCESS = `${REDUCER_ID}/SET_DISPUTE_MESSAGE_SUCCESS`;
export const SET_DISPUTE_MESSAGE_FAILURE = `${REDUCER_ID}/SET_DISPUTE_MESSAGE_FAILURE`;
